"""update grammar

Revision ID: e22a92b4e3ad
Revises: f41648ed8736
Create Date: 2024-05-17 12:18:21.117493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22a92b4e3ad'
down_revision: Union[str, None] = 'f41648ed8736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('image_id', sa.Integer(), nullable=True))
    op.drop_column('rooms', 'image_is')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('users', 'hashes_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashes_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'hashed_password')
    op.add_column('rooms', sa.Column('image_is', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'image_id')
    # ### end Alembic commands ###
